### ISSUE TITLE
Error after an attempt to create an offer

### ISSUE THREAD

**Issue by riv2q** [CodeForPoznan/volontulo#443] opened 2016-10-31 13:47 UTC
<a href="https://github.com/zuzannawiler"><img src="https://avatars.githubusercontent.com/u/15927677?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zuzannawiler](https://github.com/zuzannawiler)**
_Wednesday Feb 24, 2016 at 09:19 GMT_
_Originally opened as https://github.com/stxnext-csr/volontulo/issues/461_

----

There is a Django error displayed when a user wants to create an offer. It causes confusion since the offer is created either way and returning to the previous page a user creates the offer once again which results in multiple versions of the same offer.
![screenshot-at-09-34-13](https://cloud.githubusercontent.com/assets/15927677/13281878/85e0d868-dae6-11e5-83ea-81e9791b8a94.png)

**Comment by w1stler** [comment] 2017-02-08 20:01
Bug still occurs:

- fill all the fields except dates
- fill "Data zakończenia" with some date
- submit the form

Moving to backlog

**Comment by magul** [comment] 2017-09-12 14:25
@maddiepka can You say, what the status of this issue? There is open pull request (see #579) but there are few changes requested.

**Comment by magul** [comment] 2017-10-26 10:21
Duplicate of #719

**Closed by magul** 2017-10-26 10:21 UTC
Labels: bug, trivial
