### ISSUE TITLE
Setup testing environment

### ISSUE THREAD

**Issue by riv2q** [CodeForPoznan/volontulo#487] opened 2016-10-31 14:06 UTC
<a href="https://github.com/w1stler"><img src="https://avatars.githubusercontent.com/u/17498341?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [w1stler](https://github.com/w1stler)**
_Thursday Aug 11, 2016 at 18:23 GMT_
_Originally opened as https://github.com/stxnext-csr/volontulo/issues/574_

----

As a tester,
I want to test tickets on testing environment,
In order to ensure that all necessary work has been done

Currently we do not have testing environment, which can be built with new features that might be tested. We would like to have dev. environment, where all merged pull requests can be verified by testers. After testing we would be in position to deploy the changes to production.

**Comment by magul** [comment] 2017-09-25 20:31
Closing as duplicate of #657 adn #658

**Closed by magul** 2017-09-25 20:31 UTC
